### ISSUE TITLE
Swapped Retail Buy and Retail Sell Classification

### ISSUE THREAD

**Issue by j4ffle** [czhuuu/retail-trade#1]
Christina, looking at the data from your output and comparing it to WRDS intraday indicator files it looks like you may have swapped the classification for retail buy and sell (see the image below). The numbers for the retail trading is the same except for the label of direction of the trade. Let me know if I'm seeing things incorrectly. I really appreciate your code and how you merged HJ's and Boehmer et al. (2021)'s code. Fortunately, I don't think you use retail buys or sells in your paper.

From Boehmer et al. (2021): "If Z is in the interval (0,0.4), we identify it as a retail sell transaction. If Z is in the interval (0.6,1), the transaction is coded as a retail buy transaction." In your code around line 455 you have,
 	
`if (EX='D' and frac_penny>0 and frac_penny<0.4) then BuySellLR=1;`
`if (EX='D' and frac_penny>0.6 and frac_penny<1) then BuySellLR=-1;`
`buy_indicator=0;`
`if BuySellLR=1 then buy_indicator=1;`
`sell_indicator=0;`
'if BuySellLR=-1 then sell_indicator=1;`

![Zhu and WRDS](https://user-images.githubusercontent.com/42824678/151593259-0aa8a947-4e9c-4f1c-a666-4c6ac10efa77.PNG)
`

**Comment by czhuuu** [comment]
Thank you for noticing this issue. I've fixed the code now. Even though I didn't use retail buys and sells in our paper, the fix will hopefully help others calculate the correct measures. Much appreciated!
